import { createElement } from 'lwc';
import Child_contorl_howwork_events from 'c/child_contorl_howwork_events';

describe('c-child-contorl-howwork-events', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-child-contorl-howwork-events', {
            is: Child_contorl_howwork_events
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});