import { createElement } from 'lwc';
import Programmitaclly_parent_empoyee from 'c/programmitaclly_parent_empoyee';

describe('c-programmitaclly-parent-empoyee', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-programmitaclly-parent-empoyee', {
            is: Programmitaclly_parent_empoyee
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});